In [1]:
import pandas as pd
import geotext
import numpy as np

In [2]:
# load data
df = pd.read_excel('20180718_parsed_alabama_locations.xlsx')

In [3]:
# inspect data
df.head()

,index_ID,Date_Scraped,Ad_ID,City,Link,State,Title,Posted_Time,Posting_Body,Location,...,phone1,phone2,phone3,phone4,validAreaCode,badPhone,contains_email,Location_Status,Lat,Lon
6,6,2017-08-11,19908993,Alabama,http://alabama.backpage.com/WomenSeekMen/new-h...,Alabama,NaN,NaN,NaN,"Birmingham, Birmingham 205-760-6425",...,NaN,NaN,NaN,NaN,NaN,0,NaN,Unknown,33.5276,-86.7986
10,10,2017-08-11,22830603,Alabama,http://alabama.backpage.com/WomenSeekMen/bbw-s...,Alabama,NaN,NaN,NaN,"Auburn, Exit #62????????????????",...,NaN,NaN,NaN,NaN,NaN,0,NaN,Unknown,32.6084,-85.4897
16,16,2017-08-11,21991928,Alabama,http://alabama.backpage.com/WomenSeekMen/thick...,Alabama,NaN,NaN,NaN,"Birmingham, Irondale?Discreet Location?No OUTS",...,NaN,NaN,NaN,NaN,NaN,0,NaN,Unknown,33.5276,-86.7986
17,17,2017-08-11,21050078,Alabama,http://alabama.backpage.com/WomenSeekMen/girl-...,Alabama,NaN,NaN,NaN,"Auburn, Exit 62",...,NaN,NaN,NaN,NaN,NaN,0,NaN,Unknown,32.6084,-85.4897
20,20,2017-08-11,22783083,Alabama,http://alabama.backpage.com/WomenSeekMen/watch...,Alabama,NaN,NaN,NaN,"FaceTime me university milking birds?, Huntsville",...,NaN,NaN,NaN,NaN,NaN,0,NaN,Unknown,34.6990,-86.6412

In [4]:
# extract cities from location field
def get_city(row):
    try:
        place = geotext.GeoText(row['Location'])
        cities = set(i.title() for i in place.cities)
        return cities

    except:
        return np.nan
    
df['Location_City'] = df.apply(lambda row: get_city(row), axis=1)

In [5]:
# inspect the results
df[['Location', 'Location_City']].head(25)

,Location,Location_City
6,"Birmingham, Birmingham 205-760-6425",{Birmingham}
10,"Auburn, Exit #62????????????????",{Auburn}
16,"Birmingham, Irondale?Discreet Location?No OUTS",{Birmingham}
17,"Auburn, Exit 62",{Auburn}
20,"FaceTime me university milking birds?, Huntsville",{Huntsville}
21,"Huntsville, Huntsville area only",{Huntsville}
22,"Huntsville, Huntsville if real say your phone ...",{Huntsville}
23,"FaceTime me for real proof right now??, Huntsv...",{Huntsville}
27,"Bham, Birmingham",{Birmingham}
28,"Huntsville, Huntsville area only",{Huntsville}
29,"9184 PARKWAY ST. BIRMINGHAM 35206, Birmingham",{Birmingham}
30,"Downtown area, Montgomery",{Montgomery}
33,"Exit 6 Eastern Blvd &amp; Surrounding Areas, M...",{Montgomery}
34,"Huntsville, Huntsville AL.University","{University, Huntsville}"
37,"Birmingham, COMING TO YOU ONLY",{Birmingham}
40,"Mobile, Pascagoula//228-202-1494","{Mobile, Pascagoula}"
43,"Eastern Blvd/Upscale &amp; Discreet, Montgomery",{Montgomery}
49,"Huntsville, Huntsville area only",{Huntsville}
50,"Birmingham, hwy 280 (Birmingham)",{Birmingham}
60,"Birmingham, Birmingham hwy 280",{Birmingham}
64,"Birmingham, Surrounding areas out",{Birmingham}
65,"9533 PARKWAY EAST 35215 ? ? 205-836-20, Birmin...",{Birmingham}
67,"Mobile, Mobile &amp; Surrounding Areas",{Mobile}
69,"Montgomery, Your Place My Place",{Montgomery}
72,"Mobile, Pascagoula//228-202-1494","{Mobile, Pascagoula}"